// dashboard
export const SET_DATA = 'SET_DATA';
export const SET_CURR_PAGE = 'SET_CURR_PAGE';
export const SET_CURR_CHAR = 'SET_CURR_CHAR';
export const SET_TEXT_VISIBLE = 'SET_TEXT_VISIBLE';
export const SET_MODAL_VISIBLE = 'SET_MODAL_VISIBLE';
export const DEFAULT_DATA = {
  locName: 'unknown',
  locDimension: 'unknown',
  residentsAmount: 'unknown',
};

//login
export const SET_TOKEN = 'SET_TOKEN';

// breadcrumbs
export type Breadcrumb = {
  path: string;
  breadcrumbName: string;
};

export const routesCss = [
  {
    path: '/',
    breadcrumbName: 'HATT',
  },
  {
    path: '/unknown_css',
    breadcrumbName: 'Unknown Css Workshop',
  },
];

export const routesDashboard = [
  {
    path: '/',
    breadcrumbName: 'HATT',
  },
  {
    path: '/dashboard',
    breadcrumbName: 'Dashboard',
  },
];

const cssRulesArray = [
  'all',
  'azimuth',
  'bleed',
  'border-image',
  'bottom',
  'box-decoration-break',
  'break-after',
  'break-before',
  'break-inside',
  'caption-side',
  'caret-color',
  'clear',
  'clip',
  'color-interpolation-filters',
  'column-count',
  'column-fill',
  'column-gap',
  'column-rule',
  'column-rule-color',
  'column-rule-style',
  'column-rule-width',
  'column-span',
  'column-width',
  'columns',
  'content',
  'counter-increment',
  'counter-reset',
  'cue',
  'cue-after',
  'cue-before',
  'direction',
  'elevation',
  'empty-cells',
  'filter',
  'flood-color',
  'flood-opacity',
  'gap',
  'grid и компания',
  'hanging-punctuation',
  'hyphens',
  'image-rendering',
  'isolation',
  'lighting-color',
  'line-break',
  'list-style',
  'list-style-image',
  'list-style-position',
  'list-style-type',
  'marker-offset',
  'marks',
  'mix-blend-mode',
  'nav-down',
  'nav-left',
  'nav-right',
  'nav-up',
  'object-fit',
  'object-position',
  'order',
  'orphans',
  'overflow-wrap',
  'page',
  'page-break-after',
  'page-break-before',
  'page-break-inside',
  'pause',
  'pause-after',
  'pause-before',
  'perspective',
  'perspective-origin',
  'pitch',
  'pitch-range',
  'place-content',
  'place-items',
  'place-self',
  'play-during',
  'quotes',
  'resize',
  'rest',
  'rest-after',
  'rest-before',
  'richness',
  'right',
  'row-gap',
  'size',
  'speak',
  'speak-header',
  'speak-numeral',
  'speak-punctuation',
  'speech-rate',
  'stress',
  'tab-size',
  'table-layout',
  'text-align',
  'text-align-all',
  'text-align-last',
  'text-combine-upright',
  'text-decoration',
  'text-decoration-color',
  'text-decoration-line',
  'text-decoration-skip',
  'text-decoration-style',
  'text-indent',
  'text-justify',
  'text-orientation',
  'text-overflow',
  'text-shadow',
  'text-transform',
  'text-underline-position',
  'transform',
  'transform-box',
  'transform-origin',
  'transform-style',
  'unicode-bidi',
  'vertical-align',
  'visibility',
  'voice-balance',
  'voice-duration',
  'voice-family',
  'voice-pitch',
  'voice-range',
  'voice-rate',
  'voice-stress',
  'voice-volume',
  'volume',
  'white-space',
  'widows',
  'will-change',
  'word-break',
  'word-wrap',
  'writing-mode',
];
